### ISSUE TITLE
Disapper in options settings.

### ISSUE THREAD

**Issue by GamerPlayer888** [LorenzoPane/EvilScheme#28]
**To Reproduce**
1. Go to Cydia;
2. Update Evil Scheme 0.2.1 version to 0.2.2;
3. Restart device;
4. Go to see on options setting.

**Device:**
- iPad 5th 
- iPadOS 13.5 (17F75)
- Evil Scheme version 0.2.2

**Comment by LorenzoPane** [comment]
Sorry, but I do not plan on fixing this. If you want to access your old presets, you can downgrade and they will still be there. This change is due to transitioning to a new format for storing presets which is much more capable, and writing a converter frankly isn't worth my time or the bloat it would add to the software. Sorry :/
